export const getCommentsKey = (feedId: string) => ["comments", feedId];
export const getRepliesKey = (feedId: string, parentId: string) => ["replies", feedId, parentId];
export const getGroupsKey = () => ["groups"];
export const getFeedsKey = () => ["feeds"];
export const getMyGroupsKey = () => ["my-groups"];
export const getFeedKey = (id: string) => ["feed", id];
export const getMembersKey = (groupId: string) => ["members", groupId];
export const getUserProfileKey = (username: string) => ["user-profile", username];
export const getNotificationsKey = () => ["notifications"];
export const getGroupNotificationsKey = () => ["group-notifications"];
export const getGroupKey = (id: string) => ["group", id];
export const getSearchKey = (q?: string) => ["search", q];
export const getGroupFeedsKey = (groupId: string) => ["group-feeds", groupId];
export const getMeKey = () => ["me"];
export const getHotUsersKey = () => ["hot-users"];
export const getHotFeedsKey = () => ["hot-feeds"];
export const getMyAccountKey = () => ["my-account"];
export const getUserPostsKey = (username: string, type?: string) => ["user-posts", username, type];
export const getUserGroupsKey = (username: string) => ["user-groups", username];
export const getUserFollowersKey = (username: string) => ["user-followers", username];
export const getUserFollowingKey = (username: string) => ["user-following", username];
export const getUserCommentsKey = (username: string) => ["user-comments", username];
