/** @type {import("prettier").Config} */
module.exports = {
  bracketSpacing: true,
  bracketSameLine: false,
  singleQuote: false,
  jsxSingleQuote: false,
  trailingComma: "none",
  semi: true,
  printWidth: 120,
  arrowParens: "always",
  endOfLine: "auto",
  importOrder: [
    "",
    "<TYPES>",
    "<TYPES>^[.]",
    "^types$",
    "^@/types/(.*)$",
    "",
    ".css$",
    "",
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "<BUILTIN_MODULES>",
    "<THIRD_PARTY_MODULES>",
    "",
    "@/config/(.*)$",
    "",
    "@votewise/(.*)$",
    "",
    "@/components/(.*)$",
    "",
    "@/screens/(.*)$",
    "",
    "@/ui/(.*)$",
    "",
    "@/icons/(.*)$",
    "",
    "lib/(.*)$",
    "",
    "@/lib/(.*)$",
    "",
    "@/hooks/(.*)$",
    "",
    "@/context/(.*)$",
    "",
    "@/store/(.*)$",
    "",
    "@/utils/(.*)$",
    "",
    "@/services/(.*)$",
    "",
    "@/content/(.*)$",
    "",
    "@/app/(.*)$",
    "",
    "@/styles/(.*)$",
    "",
    "@/env(.*)$",
    "",
    "^[./]"
  ],
  importOrderTypeScriptVersion: "5.3.3",
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  plugins: ["prettier-plugin-tailwindcss", "@ianvs/prettier-plugin-sort-imports"],
  // Overrides prettier defaults for specific files
  overrides: [
    {
      files: "**/services/**/*.{ts,js,json}",
      options: {
        plugins: ["@ianvs/prettier-plugin-sort-imports"],
        importOrder: [
          "<TYPES>",
          "<TYPES>^[.]",
          "^types$",
          "^@/types/(.*)$",
          "",
          "<BUILTIN_MODULES>",
          "<THIRD_PARTY_MODULES>",
          "",
          "@votewise/(.*)$",
          "",
          "@/*/(.*)$",
          "",
          "^[./]"
        ]
      }
    }
  ]
};
