module.exports = {
  bracketSpacing: true,
  bracketSameLine: false,
  singleQuote: false,
  jsxSingleQuote: false,
  trailingComma: "es5",
  semi: true,
  printWidth: 110,
  arrowParens: "always",
  endOfLine: "auto",
  importOrder: [
    "^.+/.+.s?css$",
    "^.+\\.s?css$",
    "next",
    "^next/(.*)$",
    "react",
    "^react$",
    "^@(votewise|ee)/(.*)$",
    "components",
    "components/(.*)$",
    "lib",
    "lib/(.*)$",
    "services",
    "services/(.*)$",
    "server",
    "server/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: true,
  importOrderSortSpecifiers: true,
  plugins: [require("./merged-prettier-config")],
  overrides: [
    {
      files: "**/server/**/*.{ts,json,js}",
      options: {
        plugins: ["@trivago/prettier-plugin-sort-imports"],
        importOrder: [
          "^dotenv$",
          "^dotenv/config$",
          "^@(votewise|ee)/(.*)$",
          "@/src/(.*)$",
          "@/test/(.*)$",
          "^~/(.*)$",
          "^[./]",
        ],
      },
    },
  ],
};
